FROM nginx:alpine
COPY dist/poll-frontend-angular/browser /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT  [ "/bin/sh",  "-c",  "envsubst < /usr/share/nginx/html/environment.template.js > /usr/share/nginx/html/environment.js && exec nginx -g 'daemon off;'" ]