version: '3' 
services: 
  message: 
    image: message 
    ports: 
      - 8081:8081 
  name: 
    image: name 
    ports: 
      - 8082:8082 
    depends_on: 
      - name_db 
  name_db: 
    image: mysql 
    environment: 
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: test 
    volumes: 
      - name-db-vol:/var/lib/mysql 
  hello: 
    image: hello 
    ports: 
      - 8083:8083 
    depends_on: 
      - message 
      - name 
volumes: 
  name-db-vol: 
